# Generated by Django 5.2.8 on 2025-11-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ("-id",), "verbose_name": "ToDo Item"},
        ),
    ]
