# Generated by Django 5.2.8 on 2025-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_todoitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
